server:
  port: 8088
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  kafka:
    bootstrap-servers: localhost:9092, localhost:9093
    consumer:
      auto-offset-reset: earliest
      group-id: subscription
kafka:
  topic:
    subscription:
      request: subscription.request
      reply: subscription.reply
  request-reply:
    timeout-ms: 1000
