version: '3.5'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    restart: unless-stopped
    networks:
      - docker-network
    container_name: zookeeper-server
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - $HOME/data/zookeeper:/bitnami/zookeeper
    ports:
      - "2181:2181"

  kafka-server-1:
    image: bitnami/kafka:2.3.0
    container_name: kafka-server-1
    restart: unless-stopped
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
      - KAFKA_NUM_PARTITIONS=2
      - KAFKA_PORT_NUMBER=9092
      - KAFKA_LISTENERS=PLAINTEXT://kafka-server-1:9092,PLAINTEXT_HOST://:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server-1:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - docker-network
    volumes:
      - $HOME/data/kafka/server1:/bitnami/kafka

  kafka-server-2:
    image: bitnami/kafka:2.3.0
    container_name: kafka-server-2
    restart: unless-stopped
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=2
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
      - KAFKA_NUM_PARTITIONS=1
      - KAFKA_PORT_NUMBER=9093
      - KAFKA_LISTENERS=PLAINTEXT://kafka-server-2:9093,PLAINTEXT_HOST://:29093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server-2:9093,PLAINTEXT_HOST://localhost:29093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    ports:
      - "9093:9093"
      - "29093:29093"
    networks:
      - docker-network
    volumes:
      - $HOME/data/kafka/server2:/bitnami/kafka






networks:
  docker-network:
    driver: bridge